listeners:
  - name: ingress
    address: 0.0.0.0:8000
    protocol: http
    router: ingress_router
router:
  - name: ingress_router
    priority: 1
    rule_type: prefix
    rule_value: /
    clusters:
      - servername: demo_server
        weight: 80
        version: v1
      - servername: demo_server
        weight: 20
        version: v2
    timeout: 5000
    retry_policy:
      retry_on: true
      num_retries: 5
      try_timeout: 1000
clusters:
  - servername: demo_server
    version: v1
    endpoints:
    - 127.0.0.1:8001
    - 127.0.0.1:8002
    protocol: http
    loadbalance: rr
  - servername: demo_server
    version: v2
    endpoints:
    - 127.0.0.1:8003
    - 127.0.0.1:8004
    protocol: http
    loadbalance: rr